stages:
  - validate
  - plan
  - apply
  - destroy
image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
validate:
  stage: validate
  script:
   - terraform validate
   - export


plan:
  stage: plan
  before_script:
    - export FORTIOS_ACCESS_TOKEN=${fortigate_token}
    - export FORTIOS_ACCESS_HOSTNAME=${fortigate_hostname}
    - export FORTIOS_INSECURE ="true"
  script:
    - terraform plan -out "planfile"
    - export
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
  
apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
    - export
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script: 
    - terraform destroy -auto-approve
    - export
  dependencies:
    - apply
  when: manual